Removes a class variable that is filled from the configuration
The design was changed because it caused a NoClassDefFoundError before,
if the configuration file was incorrect. No meaningful exception was
thrown.