Update version of flyway-maven-plugin (required for newer MariaDB)
The latest version 10.15.2 cannot be used:
```
Error:  Failed to execute goal org.flywaydb:flyway-maven-plugin:10.15.2:baseline (default) on project kitodo-data-management: Execution default of goal org.flywaydb:flyway-maven-plugin:10.15.2:baseline failed: Unable to load the mojo 'baseline' in the plugin 'org.flywaydb:flyway-maven-plugin:10.15.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/flywaydb/maven/BaselineMojo has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Signed-off-by: Stefan Weil <sw@weilnetz.de>